package com.meridian.androidai.core.cognition

enum class MessageType {
    INPUT_RECEIVED,
    PERCEPTION_RESULT,
    MEMORY_QUERY,
    MEMORY_RESULT,
    KNOWLEDGE_QUERY,
    KNOWLEDGE_RESULT,
    CONTEXT_UPDATE,
    GOAL_UPDATE,
    PLAN_PROPOSAL,
    ACTION_PROPOSAL,
    AUTHORITY_CHECK,
    RESOURCE_CHECK,
    ACTION_RESULT,
    EVALUATION_RESULT,
    SELF_MODEL_UPDATE,
    STOP_REQUESTED,
    ERROR
}
